<template>
  <!-- Page Content Starts -->
  <div class="policy_page page_content">
    <div class="container">
      <!-- Policy Text-->
      <div class="row terms_texts_sec pt-md-5 bg-white">
        <div class="col-12">
          <div class="policy_text">
            <h2 style="margin-bottom: 1em;"><strong>RỦI RO</strong></h2>
              Xem xét ComfyFX ("<b>ComfyFX</b>") đồng ý ký kết các hợp đồng mua bán ngoại hối ("<b>OTC</b>") không thường xuyên ("<b>CFDs</b>") và các hợp đồng ngoại hối ("<b>Hợp đồng ngoại hối</b>") với những người ký tên dưới đây (sau đây gọi là <b>"Khách hàng", "bạn", "của bạn"</b>), Khách hàng thừa nhận, hiểu và đồng ý rằng: <strong>Thương mại là rất đầu cơ và rủi ro.</strong>
              <b>Giao dịch CFDs và Hợp đồng ngoại hối có tính đầu cơ cao, có nguy cơ mất mát đáng kể và không phù hợp với tất cả các nhà đầu tư nhưng chỉ dành cho những khách hàng:</b>
              <ul type="A">
                <li>hiểu và sẵn sàng chấp nhận các rủi ro kinh tế, pháp lý và các rủi ro khác liên quan;</li>
                <li>có kinh nghiệm và am hiểu về kinh doanh các loại chứng khoán phái sinh và trong các loại tài sản cơ bản; Và</li>
                <li>có khả năng tài chính để thừa nhận tổn thất đáng kể vượt quá biên độ hoặc ký quỹ vì các nhà đầu tư có thể mất tổng giá trị Của hợp đồng không chỉ là lợi nhuận hoặc tiền gửi.</li>
              </ul>
              CFDs và các Hợp đồng ngoại hối không phải là đầu tư thích hợp cho các quỹ hưu trí. CFD và FX là một trong những loại đầu tư rủi ro nhất và có thể dẫn đến tổn thất lớn. Khách hàng đại diện, bảo đảm và đồng ý rằng Khách hàng hiểu được những rủi ro này, sẵn sàng và có khả năng, về mặt tài chính và khác, để chấp nhận rủi ro giao dịch CFDs và Hợp đồng ngoại hối và sự mất mát toàn bộ số dư tài khoản của Khách hàng sẽ không thay đổi.
              <h4 style="margin-top: 1em;"><b>Rủi ro liên quan đến vị trí CFD dài, nghĩa là đối với Người mua của CFD</b></h4>
              Việc CFD dài hạn có nghĩa là bạn đang mua CFD trên thị trường bằng cách suy đoán rằng giá thị trường của cơ sở sẽ tăng giữa thời điểm mua và bán. Là chủ sở hữu của một vị trí lâu dài, bạn thường sẽ kiếm được lợi nhuận nếu giá thị trường của cơ sở tăng lên trong khi vị trí dài của CFD của bạn được mở. Ngược lại, bạn thường phải chịu lỗ, nếu giá thị trường của cổ phiếu giảm trong khi vị thế dài hạn của CFD của bạn là mở. Khả năng mất mát tiềm tàng của bạn có thể lớn hơn lợi nhuận ban đầu được gửi. Ngoài ra, bạn có thể bị lỗ do đóng vị trí của mình, trong trường hợp bạn không có đủ thanh khoản cho khoản ký quỹ trong tài khoản của mình để duy trì vị trí của mình.
              <h4 style="margin-top: 1em;"><b>Rủi ro liên quan đến các vị trí CFD ngắn, nghĩa là đối với người bán CFDs</b></h4>
              Việc rút ngắn CFD có nghĩa là bạn đang bán CFD trên thị trường bằng cách suy đoán rằng giá thị trường của cơ sở sẽ giảm từ thời điểm mua bán. Là chủ sở hữu của một vị trí ngắn, bạn thường sẽ kiếm được lợi nhuận nếu giá thị trường của cơ sở nằm trong khi vị trí CFD của bạn đang mở. Ngược lại, bạn thường phải chịu lỗ, nếu giá thị trường của cơ sở tăng lên trong khi vị trí CFD của bạn đang mở. Khả năng mất mát tiềm tàng của bạn có thể lớn hơn lợi nhuận ban đầu được gửi. Ngoài ra, bạn có thể bị lỗ do đóng vị trí của mình, trong trường hợp bạn không có đủ thanh khoản cho khoản ký quỹ trong tài khoản của mình để duy trì vị trí của mình.
              <h4 style="margin-top: 1em;"><b>Leverage cao và Margin thấp có thể dẫn đến mất mát nhanh</b></h4>
              <ul>
                <li>Mức độ “gearing” hoặc “leverage” cao là một đặc điểm của hợp đồng CFDs và FX. Ảnh hưởng của đòn bẩy làm cho việc đầu tư vào CFD trở nên rủi ro hơn là đầu tư vào tài sản cơ bản.</li>
                <li>Điều này có thể vừa thuận lợi vừa bất lợi. Một sự dao động giá nhỏ trong vùng lợi nhuận của bạn có thể mang lại lợi tức cao cho khoản tiền gửi, tuy nhiên, một đợt giá nhỏ chống lại bạn có thể dẫn đến tổn thất đáng kể. Các khoản lỗ của bạn sẽ không bao giờ vượt quá số dư tài khoản của bạn, số tiền này được cân bằng với số không, nếu tổn thất cao hơn số tiền gửi. Những tổn thất như vậy có thể xảy ra nhanh chóng. Đòn bẩy càng lớn thì rủi ro càng lớn. Kích thước của đòn bẩy do đó một phần xác định kết quả đầu tư.</li>
              </ul>
              <h4 style="margin-top: 1em;"><b>Yêu cầu ký quỹ</b></h4>
              Khách hàng phải duy trì yêu cầu tối thiểu về ký quỹ trên các vị trí mở của mình mọi lúc. Khách hàng có trách nhiệm theo dõi số dư tài khoản của mình. Khách hàng có thể nhận được một cuộc gọi ký quỹ để đặt cọc thêm tiền nếu biên trong tài khoản có liên quan quá thấp. ComfyFX có quyền thanh lý bất kỳ hoặc tất cả các vị trí mở bất cứ khi nào yêu cầu ký quỹ tối thiểu không được duy trì và điều này có thể làm cho CFDs của khách hàng hoặc Hợp đồng ngoại hối bị đóng cửa vì tổn thất mà bạn sẽ phải chịu trách nhiệm pháp lý.
              <h4 style="margin-top: 1em;"><b>Spread</b></h4>
              <ul>
                <li>Sự khác biệt giữa giá dự thầu và giá yêu cầu của chúng tôi là “Spread của chúng tôi”. Spread của chúng tôi được đặt theo quyết định tuyệt đối của chúng tôi, vì chúng tôi đóng vai trò là nhà sản xuất thị trường và mọi thay đổi đều có hiệu lực ngay lập tức.</li>
                <li>Thông tin liên quan đến Spread của chúng tôi, đòn bẩy, phí di chuyển và giờ giao dịch cho mỗi thị trường được nêu trong Điều kiện giao dịch CFD và điều kiện giao dịch FX của trang web ComfyFX.</li>
              </ul>
              <h4 style="margin-top: 1em;"><b>Thanh toán tiền mặt</b></h4>
              Khách hàng hiểu rằng hợp đồng CFD và FX chỉ có thể được giải quyết bằng tiền mặt và sự khác biệt giữa giá mua và bán một phần quyết định kết quả đầu tư.
              <h4 style="margin-top: 1em;"><b>Xung đột lợi ích</b></h4>
              ComfyFX là đối tác của tất cả các Giao dịch được ký kết theo Thỏa thuận khách hàng và vì vậy, các lợi ích của ComfyFX có thể xung đột với bạn. Chính sách Mâu thuẫn Quyền lợi của chúng tôi có tại trang web của ComfyFX.
              <h4 style="margin-top: 1em;"><b>Giao dịch OTC</b></h4>
              Khi giao dịch hợp đồng CFDs hoặc FX với chúng tôi, các giao dịch đó sẽ không được thực hiện trên một giao dịch đầu tư được công nhận hoặc được chỉ định và được gọi là các giao dịch OTC. Tất cả các vị trí nhập vào với chúng tôi phải đóng cửa với chúng tôi và không thể đóng cửa với bất kỳ thực thể khác. Các giao dịch OTC có thể gây rủi ro lớn hơn việc đầu tư vào các hợp đồng giao dịch hối đoái vì không có thị trường ngoại hối để đóng một vị trí mở. Có thể không thể thanh lý một vị trí hiện tại, để đánh giá giá trị của vị trí phát sinh từ giao dịch OTC hoặc để đánh giá mức độ rủi ro. Chúng tôi có thể không trích dẫn giá thầu và giá chào bán dựa trên chính sách thực hiện tốt nhất áp dụng trên thị trường. Không có thanh toán bù trừ trung tâm và không có bất kỳ cam kết nào của bên khác về nghĩa vụ thanh toán của ComfyFX cho Khách hàng, do đó Khách hàng có rủi ro tín dụng với ComfyFX. Khách hàng chỉ phải xem xét đến ComfyFX để thực hiện tất cả các hợp đồng trong tài khoản của Khách hàng và trả lại bất kỳ khoản ký quỹ hoặc tài sản thế chấp.
              <h4 style="margin-top: 1em;"><b>Giá cả, mức chênh lệch và giá trị được xác định bởi ComfyFX và có thể khác với giá báo cáo ở những nơi khác</b></h4>
              <ul>
                <li>ComfyFX sẽ cung cấp giá được sử dụng trong kinh doanh, định giá các vị trí của Khách hàng và xác định các yêu cầu Margin theo các Chính sách và Thủ tục Thương mại của nó và Các Bảng thông tin Thị trường. Việc thực hiện Hợp đồng CFD hoặc FX của bạn sẽ tùy thuộc vào giá do ComfyFX đặt ra và biến động của thị trường trong tài sản cơ bản mà hợp đồng của bạn liên quan. Do đó mỗi tài sản cơ bản mang những rủi ro cụ thể có ảnh hưởng đến kết quả của CFD có liên quan.</li>
                <li>Giá của chúng tôi cho một thị trường cụ thể được tính bằng cách tham khảo giá của tài sản cơ bản có liên quan mà chúng tôi nhận được từ các nguồn tham chiếu bên ngoài bên thứ ba hoặc trao đổi. Đối với CFD và Hợp đồng ngoại hối của chúng tôi, chúng tôi thu được dữ liệu giá cả từ những người tham gia thị trường bán buôn. Mặc dù ComfyFX hy vọng rằng những mức giá này có liên quan hợp lý đến giá có sẵn trên thị trường, giá ComfyFX có thể khác với giá có sẵn cho các ngân hàng và những người tham gia thị trường khác. ComfyFX có quyền quyết định đáng kể trong việc thiết lập và thu lợi nhuận. ComfyFX được ủy quyền để chuyển tiền trong tài khoản của Khách hàng cho khoản ký quỹ vào và từ ngoại tệ đó theo tỷ giá hối đoái được xác định bởi ComfyFX theo quyết định riêng của mình dựa trên tỷ giá thị trường tiền tệ hiện hành.</li>
              </ul>
              <h4 style="margin-top: 1em;"><b>Quyền sở hữu các tài sản cơ sở</b></h4>
              Bạn không có quyền hoặc nghĩa vụ đối với các công cụ hoặc tài sản tiềm ẩn có liên quan đến CFDs hoặc Hợp đồng ngoại hối của bạn. Khách hàng hiểu rằng các CFD có thể có các tài sản cơ bản khác như chứng khoán, chỉ số, tiền tệ và hàng hóa, như đã nêu trong Điều kiện giao dịch CFD và điều kiện giao dịch FX trong trang web của ComfyFX.
              <h4 style="margin-top: 1em;"><b>Rủi ro tiền tệ</b></h4>
              Đầu tư vào các Hợp đồng ngoại hối và CFD với một tài sản cơ bản được liệt kê bằng một đơn vị tiền tệ không phải là loại tiền tệ cơ sở của bạn có nguy cơ về tiền tệ, do thực tế là khi hợp đồng CFD hoặc FX được thanh toán bằng một loại tiền tệ khác với loại tiền tệ cơ sở của bạn, Lợi tức có thể bị ảnh hưởng bởi việc chuyển đổi sang tiền tệ cơ sở.
              <h4 style="margin-top: 1em;"><b>Một Click vào Giao dịch và ngay lập tức khớp lệnh</b></h4>
              Hệ thống Giao dịch Trực tuyến của ComfyFX cung cấp ngay lập tức chuyển đơn hàng của Khách hàng khi Khách hàng nhập vào số tiền và nhấp vào “Mua / Bán”. Điều này có nghĩa là không có cơ hội để xem lại đơn đặt hàng sau khi nhấp vào “Mua / Bán” và Đơn hàng Thị trường không thể bị hủy hoặc sửa đổi . Tính năng này có thể khác với các hệ thống giao dịch khác mà bạn đã sử dụng. Khách hàng nên sử dụng Hệ thống Giao dịch Demo để làm quen với Hệ thống Giao dịch trực tuyến trước khi thực sự giao dịch trực tuyến với ComfyFX. Khách hàng thừa nhận và đồng ý rằng bằng cách sử dụng Hệ thống Giao dịch Trực tuyến của ComfyFX, Khách hàng đồng ý với hệ thống một cú nhấp chuột và chấp nhận rủi ro của tính năng truyền / thực hiện ngay lập tức này.
              <h4 style="margin-top: 1em;"><b>Đơn đặt hàng Điện thoại và Thực hiện Ngay</b></h4>
              Đơn đặt hàng thị trường được thực hiện qua điện thoại thông qua ComfyFX Trading Desk được hoàn thành khi nhà khai thác điện thoại của ComfyFX nói “thỏa thuận” hoặc “thực hiện” sau khi Khách hàng đặt hàng. Khi có xác nhận của nhà khai thác điện thoại, Khách Hàng đã mua hoặc bán và không thể hủy Lệnh Thị trường. Bằng cách đặt Đơn đặt hàng Thị trường qua Bàn Giao dịch ComfyFX, Khách hàng thừa nhận và đồng ý thực hiện ngay lập tức và chấp nhận rủi ro về tính năng thực hiện ngay lập tức này.
              <h4 style="margin-top: 1em;"><b>ComfyFX không phải là Cố vấn hay Người được uỷ thác cho Khách hàng</b></h4>
              Trong trường hợp ComfyFX cung cấp các khuyến nghị về thị trường chung, các khuyến nghị chung này không phải là một lời khuyên cá nhân hoặc tư vấn đầu tư và không xem xét bất kỳ hoàn cảnh cá nhân hoặc mục tiêu đầu tư nào của bạn, cũng không phải là một đề nghị mua hoặc bán, hoặc chào mời một đề nghị Mua hay bán, bất kỳ Hợp đồng ngoại hối hoặc Hợp đồng chéo. Mỗi quyết định của Khách hàng để tham gia vào Hợp đồng CFD hoặc FX với ComfyFX và mỗi quyết định về việc một giao dịch phù hợp với Khách hàng là một quyết định độc lập do Khách hàng thực hiện. ComfyFX không hoạt động với tư cách là cố vấn hoặc là người ủy thác cho Khách hàng. Khách hàng đồng ý rằng ComfyFX không có nghĩa vụ ủy thác đối với Khách hàng và không có nghĩa vụ liên quan và không chịu trách nhiệm đối với bất kỳ khoản nợ, yêu cầu bồi thường, tổn thất, chi phí nào, bao gồm phí luật sư, phát sinh liên quan đến Khách hàng theo khuyến nghị thương mại chung của ComfyFX hoặc Không thực hiện bất kỳ hành động nào dựa trên các khuyến nghị chung hoặc thông tin do ComfyFX cung cấp.
              <h4 style="margin-top: 1em;"><b>Đề xuất không đảm bảo</b></h4>
              Các khuyến nghị thị trường chung do ComfyFX cung cấp chỉ dựa trên phán quyết của nhân viên ComfyFX và nên được xem như vậy. Khách hàng thừa nhận rằng Khách hàng tham gia bất kỳ Giao dịch nào dựa vào phán quyết của Khách hàng. Bất kỳ khuyến nghị thị trường nào cung cấp chỉ là chung chung và có thể hoặc không phù hợp với các vị trí thị trường hoặc ý định của ComfyFX và / hoặc các chi nhánh của ComfyFX. Các khuyến nghị về thị trường chung của ComfyFX dựa trên các thông tin tin cậy, nhưng ComfyFX không thể và không đảm bảo tính chính xác hoặc đầy đủ của nó hoặc đại diện cho rằng sau những khuyến nghị chung như vậy sẽ làm giảm hoặc loại bỏ rủi ro vốn có của CFDs và / hoặc hợp đồng FX.
              <h4 style="margin-top: 1em;"><b>Không có bảo đảm lợi nhuận</b></h4>
              Không có đảm bảo về lợi nhuận cũng không phải tránh thất thoát khi kinh doanh CFDs và hợp đồng FX. Khách hàng không nhận được bảo lãnh như vậy từ ComfyFX hoặc từ bất kỳ đại diện nào của ComfyFX. Khách hàng nhận thức được những rủi ro vốn có trong giao dịch CFDs và Hợp đồng ngoại hối và có khả năng chịu được rủi ro như vậy và chịu được mọi thiệt hại phát sinh.
              <h4 style="margin-top: 1em;"><b>Khách hàng có thể không có khả năng đóng các vị trí mở</b></h4>
              Do các điều kiện thị trường có thể gây ra biến động giá bất thường và nhanh chóng hoặc các trường hợp khác, ComfyFX có thể không thể đóng vị trí của Khách hàng ở mức giá được chỉ định bởi Khách hàng và các kiểm soát rủi ro do ComfyFX quy định sẽ không có tác dụng và Khách hàng đồng ý rằng ComfyFX sẽ Không phải chịu trách nhiệm về việc không làm như vậy.
              <h4 style="margin-top: 1em;"><b>Kinh doanh qua Internet</b></h4>
              Khi Khách hàng giao dịch trực tuyến (thông qua internet), ComfyFX sẽ không chịu trách nhiệm về bất kỳ khiếu nại, tổn thất, thiệt hại, chi phí hoặc chi phí gây ra, trực tiếp hoặc gián tiếp, bởi bất kỳ sự cố, gián đoạn hoặc thất bại của bất kỳ hệ thống truyền tải, truyền thông, Phần mềm giao dịch, dù thuộc về ComfyFX, Khách hàng, bất kỳ trao đổi hoặc bất kỳ hệ thống thanh toán hoặc bù trừ nào.
              <h4 style="margin-top: 1em;"><b>Đơn đặt hàng qua điện thoại</b></h4>
              ComfyFX không chịu trách nhiệm về sự gián đoạn, thất bại hoặc sự cố của các thiết bị điện thoại và không đảm bảo tính sẵn có của điện thoại. Để tránh nghi ngờ, Khách hàng biết rằng ComfyFX có thể không thể liên lạc bằng điện thoại vào mọi lúc. Trong những trường hợp như vậy khách hàng sẽ đặt hàng của mình thông qua các phương tiện khác được cung cấp bởi ComfyFX.
              <h4 style="margin-top: 1em;"><b>Lỗi báo trích dẫn</b></h4>
              Nếu một lỗi báo giá xảy ra (bao gồm phản hồi các yêu cầu của Khách hàng), ComfyFX sẽ không chịu trách nhiệm về bất kỳ lỗi kết quả nào trong số dư tài khoản và có quyền thực hiện các sửa đổi hoặc điều chỉnh cần thiết cho Tài khoản có liên quan. Bất kỳ tranh chấp phát sinh từ những lỗi nêu trên sẽ được giải quyết trên cơ sở giá trị thị trường hợp lý theo quyết định của ComfyFX và hành động một cách thiện chí của thị trường liên quan vào thời điểm có lỗi xảy ra. Trong trường hợp thị trường phổ biến đại diện cho giá khác với giá ComfyFX đã đăng trên màn hình của chúng tôi, ComfyFX sẽ cố gắng, trên cơ sở nỗ lực tốt nhất, để thực hiện Giao dịch trên hoặc gần với giá thị trường hiện hành. Các mức giá thị trường hiện hành sẽ là giá, và cuối cùng được phản ánh trên các báo cáo của Khách hàng. Điều này có thể hoặc không ảnh hưởng xấu đến lợi nhuận và tổn thất đã thực hiện và chưa thực hiện của Khách hàng.


              <strong>TÔI/ CHÚNG TÔI ĐÃ ĐỌC, HIỂU RÕ VÀ ĐỒNG Ý VỚI BÁO CÁO CÔNG BỐ RỦI RO VÀ CÁC CHÍNH SÁCH VÀ THỦ TỤC KINH DOANH ĐÃ Ở TRÊN</strong>


          </div>
        </div>
      </div>
      <!-- Policy Text Ends-->
    </div>
  </div>
  <!-- Page Content Ends -->
</template>
